<?php if (5 == $this->column_id and 'fia' != $this->type) { // 代表人姓名 ?>
<a href="/name/<?= urlencode(json_decode($this->value)) ?>"><?= $this->escape(json_decode($this->value)) ?></a>
<?php } elseif (11 == $this->column_id and 'fia' != $this->type) { // 董監事名單 ?>
<ol>
    <?php foreach (json_decode($this->value) as $row) { ?>
    <li value="<?= $this->escape($row->{'序號'}) ?>">
    <?= $this->escape($row->{'職稱'}) ?>
    , 姓名: 
    <a href="/name/<?= urlencode($row->{'姓名'}) ?>"><?= $this->escape($row->{'姓名'}) ?></a>
    <?php if (is_array($row->{'所代表法人'})) { ?>
    (所代表法人:
    <a href="/fund/<?= urlencode($row->{'所代表法人'}[1]) ?>"><?= $this->escape(implode(', ', $row->{'所代表法人'})) ?></a>)
    <?php } elseif ($row->{'所代表法人'}) { ?>
    (所代表法人:
    <?= $this->escape($row->{'所代表法人'}) ?>)
    <?php } ?>
    <?php if (preg_match('#有限公司$#', $this->name) and !preg_match('#股份有限公司$#', $this->name)){ ?>
    , 出資額:
    <?php } else { ?>
    , 持有股份數:
    <?php } ?>
    <?= $this->escape($row->{'出資額'}) ?>
    </li>
    <?php } ?>
</ol>
<?php } elseif (12 == $this->column_id and 'fia' != $this->type) { // 經理人名單 ?>
<ol>
    <?php foreach (json_decode($this->value) as $row) { ?>
    <li value="<?= $this->escape($row->{'序號'}) ?>">
    姓名: 
    <a href="/name/<?= urlencode($row->{'姓名'}) ?>"><?= $this->escape($row->{'姓名'}) ?></a>
    , 到職日期:
    <?= $this->escape(json_encode($row->{'到職日期'}, JSON_UNESCAPED_UNICODE)) ?>
    </li>
    <?php } ?>
</ol>
<?php } elseif (50 == $this->column_id and 'fia' != $this->type) { // 總公司統編 ?>
<?php if ($unit = Unit::find(json_decode($this->value))) { ?>
<a href="/id/<?= $unit->id ?>"><?= $unit->id() ?>.<?= $this->escape($unit->name()) ?></a>
<?php } else { ?>
<?= $this->escape(json_decode($this->value)) ?>
<?php } ?>
<?php } elseif ('[' == $this->value[0]) { // array ?>
<ul>
    <?php foreach (json_decode($this->value) as $row) { ?>
    <li><?= $this->escape(json_encode($row,  JSON_UNESCAPED_UNICODE)) ?></li>
    <?php } ?>
</ul>
<?php } elseif ('"' == $this->value[0]) { ?>
<?= $this->escape(json_decode($this->value)) ?>
<?php } else { ?>
<?= $this->escape($this->value) ?>
<?php } ?>
