<?php

list($updated_at, $count) = explode(',', KeyValue::get('data_update'));
?>
<?= $this->partial('/common/header.phtml', $this) ?>
<h1>關於本站</h1>
本站內資料來自<a href="http://gcis.nat.gov.tw/">經濟部商業司</a>及<a href="https://www.etax.nat.gov.tw/etwmain/front/ETW113W1">財政部營業稅籍資料</a>，主要是提供另一個介面來讓大家更容易了解台灣的公司以及商業登記資訊。
<div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <strong>
        [2023/01/24 公告] 目前 Ronny Wang 推出訂閱贊助方案了，如果你覺得 Ronny 的一些開放政府專案有幫助到你，或者希望看到 Ronny 做更多的專案，歡迎到 <a href="https://www.patreon.com/ronnywang">www.patreon.com/ronnywang</a> 訂閱贊助，Ronny 也會在 Patreon 上面提供一些開放資料相關的更新以訂閱贊助者專屬的回饋喔。如果想要捐款單次贊助也可以到 <a href="https://ronny.tw/#donate">贊助 Ronny</a>，所有的收支明細都會 <a href="https://docs.google.com/spreadsheets/d/1WOYz7N4QaW1-0NmLzrqboIfgcvlnKCnFs1uru2O6PjQ/edit#gid=0">公開</a> 喔，謝謝您的支持
    </strong>
</div>


<h1>注意事項</h1>
<ol>
    <li>經濟部資料更新頻率為每月10日更新前一個月資料，更新來源為經濟部商業司<a href="http://gcis.nat.gov.tw/pub/cmpy/report.jsp" target="_blank">公司登記資料相關清冊下載</a></li>
    <li>財政部資料更新頻率為每日一次，更新來源為 <a href="http://data.gov.tw/node/9400" target="_blank">政府資料開放平台-全國營業(稅籍)登記資料集</a></li>
    <li>本站資料可能有未即時更新，正確資料請以各結果頁面上的「原始連結」內資料為準</li>
    <li>人名搜尋公司可能會有同名同姓但是其實是不同人的情況，若要確認是否為同一人請進一步至經濟部商業司查詢</li>
    <li>2019年10月經濟部商業司舊版公司登記查詢網站下線，相關異動可參考<a href="https://g0v.hackmd.io/I78huXsgTk6EPFYLRl882g" target="_blank">這裡</a></li>
    <li>最近資料更新日期：<?= date('Y-m-d', $updated_at) ?>（更新公司數：<?= $count ?>)</li>
</ol>
<?= $this->partial('/common/footer.phtml', $this) ?>
