<?php
$this->pagerBaseUri = '/name/' . urlencode($this->search_word) . '?page=%d';
?>
<?= $this->partial('/common/header.phtml', $this) ?>
<h2>搜尋，姓名 「<?= $this->escape($this->search_word) ?>」的結果，一共 <?= $this->search_result->hits->total ?> 筆</h2>
<?= $this->partial('index/search_table.phtml', array('search_result' => $this->search_result)) ?>
<?= $this->partial('/common/pager.phtml', $this) ?>
<?= $this->partial('/common/footer.phtml', $this) ?>
