<?php
?>
<?= $this->partial('/common/header.phtml', $this) ?>
<h2>搜尋，「<?= $this->escape($this->search_word) ?>」的結果，一共 <?= $this->search_result->hits->total ?> 筆</h2>
<table class="table">
    <tr>
        <td>No.</td>
        <td>名稱</td>
        <td>負責人/代表人</td>
        <td>地址</td>
        <td>登記機關</td>
        <td>狀況</td>
    </tr>
    <?php foreach ($this->search_result->hits->hits as $hit) { ?>
    <?php $unit = Unit::find($hit->_id) ?>
    <tr>
        <td><a href="/id/<?= $unit->id() ?>"><?= $unit->id() ?></a></td>
        <td><?= $this->escape($unit->name()) ?></td>
        <?php if (1 == $unit->type) { ?>
        <td>
            <?php if ($unit->get('代表人姓名')) { ?>
            <?= $this->partial('/index/data_show.phtml', array('value' => $unit->get('代表人姓名')->value)) ?>
            <?php } elseif ($unit->get('訴訟及非訴訟代理人姓名')) { ?>
            <?= $this->partial('/index/data_show.phtml', array('value' => $unit->get('訴訟及非訴訟代理人姓名')->value)) ?>
            <?php } ?>
        </td>
        <td>
            <?php if ($unit->get('公司所在地')) { ?>
            <?= $this->partial('/index/data_show.phtml', array('value' => $unit->get('公司所在地')->value)) ?>
            <?php } elseif ($unit->get('辦事處所在地')) { ?>
            <?= $this->partial('/index/data_show.phtml', array('value' => $unit->get('辦事處所在地')->value)) ?>
            <?php } elseif ($unit->get('分公司所在地')) { ?>
            <?= $this->partial('/index/data_show.phtml', array('value' => $unit->get('分公司所在地')->value)) ?>
            <?php } ?>
        </td>
        <td>
            <?= $this->partial('/index/data_show.phtml', array('value' => $unit->get('登記機關')->value)) ?>
        </td>
        <td>
            <?= $this->partial('/index/data_show.phtml', array('value' => $unit->get('公司狀況')->value)) ?>
        </td>
        <?php } elseif (2 == $unit->type) { ?>
        <td>
            <?= $this->partial('/index/data_show.phtml', array('value' => $unit->get('負責人姓名')->value)) ?>
        </td>
        <td>
            <?= $this->partial('/index/data_show.phtml', array('value' => $unit->get('地址')->value)) ?>
        </td>
        <td>
            <?= $this->partial('/index/data_show.phtml', array('value' => $unit->get('登記機關')->value)) ?>
        </td>
        <td>
            <?= $this->partial('/index/data_show.phtml', array('value' => $unit->get('現況')->value)) ?>
        </td>
        <?php } else { ?>
        <td></td>
        <td></td>
        <td></td>
        <?php } ?>
    </tr>
    <?php } ?>
</table>
<?php if ($this->page > 1) { ?>
<a href="/index/search?q=<?= urlencode($this->search_word) ?>&page=<?= $this->page - 1 ?>">上一頁</a>
<?php } else { ?>
上一頁
<?php } ?>
| <?= $this->page ?> |
<?php if ($this->page < $this->max_page) { ?>
<a href="/index/search?q=<?= urlencode($this->search_word) ?>&page=<?= $this->page + 1 ?>">下一頁</a>
<?php } else { ?>
下一頁
<?php } ?>
<?= $this->partial('/common/footer.phtml', $this) ?>
