<?php
$this->title = $this->unit->name() . ':' . $this->unit->id() . ':';
?>
<?= $this->partial('/common/header.phtml', $this) ?>
<a href="/index/redirect?type=<?= $this->unit->type ?>&id=<?= $this->unit->id ?>&gcis.nat.gov.tw">原始資料</a>
<table border="1">
    <tr>
        <td>欄位</td>
        <td>值</td>
    </tr>
    <tr>
        <td>API URL</td>
        <td>http://<?= $_SERVER['HTTP_SERVER'] ?>/api/show/<?= $this->unit->id() ?></td>
    </tr>
    <tr>
        <td>ID</td>
        <td><?= $this->unit->id() ?></td>
    </tr>
    <tr>
        <td>Updated_at</td>
        <td><?= date('c', $this->unit->updated_at) ?></td>
    </tr>
    <?php foreach (UnitData::search(array('id' => $this->unit->id)) as $unitdata) { ?>
    <tr>
        <td><?= ColumnGroup::getColumnName($unitdata->column_id) ?></td>
        <td><?= $this->partial('/index/data_show.phtml', array('value' => $unitdata->value, 'column_id' => $unitdata->column_id)) ?></td>
    </tr>
    <?php } ?>
</table>
<?= $this->partial('/common/footer.phtml', $this) ?>
